Traceback (most recent call last):
Traceback (most recent call last):
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 631, in <module>
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 631, in <module>
Traceback (most recent call last):
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 631, in <module>
Traceback (most recent call last):
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 631, in <module>
        main()main()
    
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 621, in main
main()  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 621, in main

  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 621, in main
    trainer = Trainer(cfg)
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 159, in __init__
    trainer = Trainer(cfg)    
trainer = Trainer(cfg)  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 159, in __init__

  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 159, in __init__
    model = SamudraBGC(
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/models/samudra_bgc.py", line 65, in __init__
        main()    model = SamudraBGC(
model = SamudraBGC(
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 621, in main

  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/models/samudra_bgc.py", line 65, in __init__
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/models/samudra_bgc.py", line 65, in __init__
    trainer = Trainer(cfg)
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 159, in __init__
    model = SamudraBGC(
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/models/samudra_bgc.py", line 65, in __init__
    create_block(
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/models/factory.py", line 37, in create_block
    create_block(
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/models/factory.py", line 37, in create_block
    create_block(
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/models/factory.py", line 37, in create_block
    create_block(
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/models/factory.py", line 37, in create_block
    return BLOCK_REGISTRY[block_type](**kwargs)
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/models/blocks.py", line 97, in __init__
    return BLOCK_REGISTRY[block_type](**kwargs)
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/models/blocks.py", line 97, in __init__
    return BLOCK_REGISTRY[block_type](**kwargs)    
return BLOCK_REGISTRY[block_type](**kwargs)  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/models/blocks.py", line 97, in __init__

  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/models/blocks.py", line 97, in __init__
    assert n_layers == 1, "Can only use a single layer here!"
AssertionError: Can only use a single layer here!
    assert n_layers == 1, "Can only use a single layer here!"
AssertionError: Can only use a single layer here!
    assert n_layers == 1, "Can only use a single layer here!"
AssertionError: Can only use a single layer here!
    assert n_layers == 1, "Can only use a single layer here!"
AssertionError: Can only use a single layer here!
[2025-09-05 22:06:49,841] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 164748 closing signal SIGTERM
[2025-09-05 22:06:50,005] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 164745) of binary: /home/mk0964/.conda/envs/samudra/bin/python
Traceback (most recent call last):
  File "/home/mk0964/.conda/envs/samudra/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
src/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-09-05_22:06:49
  host      : tiger-i04g1
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 164746)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-09-05_22:06:49
  host      : tiger-i04g1
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 164747)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-09-05_22:06:49
  host      : tiger-i04g1
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 164745)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
